version: 2
jobs:
  build:
    docker:
          - image: circleci/node:8.11.3 
        steps:
          - checkout # check out the code in the project directory
          - run: echo "hello world" # run the `echo` command
          - run: npm install 
          - run: npm run build
          - run: npm start
       
