
version: 2
jobs:
  build:
    docker: # use the docker executor type; machine and macos executors are also supported
      - image: circleci/node:8.11.3 # the primary container, where your job's commands are run
    working_directory: ~/ci
    steps:
      - checkout # check out the code in the project directory
      - run: npm run build
  deploy_heroku:
    docker: # use the docker executor type; machine and macos executors are also supported
      - image: circleci/node:8.11.3  
    steps:
      - checkout
      - run:
          name: Deploy Master to Heroku
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master
workflows:
  version: 2
  deploys:
    jobs:
      - build
      - deploy_heroku:
          requires:
            - build
          filters:
            branches:
              only: master

   
#     steps:
#       - checkout
#       - run:
#           name: Deploy Master to Heroku
#           command: |
#             git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master
